"""empty message

Revision ID: e6474e68668d
Revises: 6e71b9f09d44
Create Date: 2019-07-22 02:33:07.359087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6474e68668d'
down_revision = '6e71b9f09d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_first_name', table_name='users')
    op.drop_index('ix_users_last_name', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=60), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=60), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('is_admin IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=False)
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    # ### end Alembic commands ###
